name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']
        php-version: ['8.1']

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm install

      # Run tests for Node.js
      - name: Run Node.js tests
        run: npm test

      # Set up PHP environment (if needed for Laravel or other PHP projects)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      # Install Composer dependencies (if using PHP/Laravel)
      - name: Install Composer dependencies
        run: composer install

      # Run tests for PHP (if applicable)
      - name: Run PHP tests
        run: php artisan test

      # Optional: Linting or any other checks
      - name: Run Lint
        run: npm run lint
